In [1]:
import pandas as pd

# Yöntem 1: raw string (r işareti ile - en pratik)
df = pd.read_csv(r"C:\Users\nazlican\OneDrive\Masaüstü\owid-covid-data.csv")

print(df.shape)
print(df.columns.tolist())
df.head()

(429435, 67)
['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred', 'stringency_index', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'population', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  object
 1   continent                                   402910 non-null  object
 2   location                                    429435 non-null  object
 3   date                                        429435 non-null  object
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: float64(61), int64(1), object(5)
memory usage: 219.5+ MB

In [3]:
'''
 0   iso_code                                    429435 non-null  object 
 1   continent                                   402910 non-null  object 
 2   location                                    429435 non-null  object 
 3   date                                        429435 non-null  object 
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object 
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64  
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64

'''

'\n 0   iso_code                                    429435 non-null  object \n 1   continent                                   402910 non-null  object \n 2   location                                    429435 non-null  object \n 3   date                                        429435 non-null  object \n 4   total_cases                                 411804 non-null  float64\n 5   new_cases                                   410159 non-null  float64\n 6   new_cases_smoothed                          408929 non-null  float64\n 7   total_deaths                                411804 non-null  float64\n 8   new_deaths                                  410608 non-null  float64\n 9   new_deaths_smoothed                         409378 non-null  float64\n 10  total_cases_per_million                     411804 non-null  float64\n 11  new_cases_per_million                       410159 non-null  float64\n 12  new_cases_smoothed_per_million              408929 non-null  float64\n 13  total_deaths_per_million                    411804 non-null  float64\n 14  new_deaths_per_million                      410608 non-null  float64\n 15  new_deaths_smoothed_per_million             409378 non-null  float64\n 16  reproduction_rate                           184817 non-null  float64\n 17  icu_patients                                39116 non-null   float64\n 18  icu_patients_per_million                    39116 non-null   float64\n 19  hosp_patients                               40656 non-null   float64\n 20  hosp_patients_per_million                   40656 non-null   float64\n 21  weekly_icu_admissions                       10993 non-null   float64\n 22  weekly_icu_admissions_per_million           10993 non-null   float64\n 23  weekly_hosp_admissions                      24497 non-null   float64\n 24  weekly_hosp_admissions_per_million          24497 non-null   float64\n 25  total_tests                                 79387 non-null   float64\n 26  new_tests                                   75403 non-null   float64\n 27  total_tests_per_thousand                    79387 non-null   float64\n 28  new_tests_per_thousand                      75403 non-null   float64\n 29  new_tests_smoothed                          103965 non-null  float64\n 30  new_tests_smoothed_per_thousand             103965 non-null  float64\n 31  positive_rate                               95927 non-null   float64\n 32  tests_per_case                              94348 non-null   float64\n 33  tests_units                                 106788 non-null  object \n 34  total_vaccinations                          85417 non-null   float64\n 35  people_vaccinated                           81132 non-null   float64\n 36  people_fully_vaccinated                     78061 non-null   float64\n 37  total_boosters                              53600 non-null   float64\n 38  new_vaccinations                            70971 non-null   float64\n 39  new_vaccinations_smoothed                   195029 non-null  float64\n 40  total_vaccinations_per_hundred              85417 non-null   float64\n 41  people_vaccinated_per_hundred               81132 non-null   float64\n 42  people_fully_vaccinated_per_hundred         78061 non-null   float64\n 43  total_boosters_per_hundred                  53600 non-null   float64\n 44  new_vaccinations_smoothed_per_million       195029 non-null  float64\n 45  new_people_vaccinated_smoothed              192177 non-null  float64\n 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64\n 47  stringency_index                            196190 non-null  float64\n 48  population_density                          360492 non-null  float64\n 49  median_age                                  334663 non-null  float64\n 50  aged_65_older                               323270 non-null  float64\n 51  aged_70_older                               331315 non-null  float64\n 52  gdp_per_capita                              328292 non-null  float64\n 53  extreme_poverty                             211996 non-null  float64\n 54  cardiovasc_death_rate                       328865 non-null  float64\n 55  diabetes_prevalence                         345911 non-null  float64\n 56  female_smokers                              247165 non-null  float64\n 57  male_smokers                                243817 non-null  float64\n 58  handwashing_facilities                      161741 non-null  float64\n 59  hospital_beds_per_thousand                  290689 non-null  float64\n 60  life_expectancy                             390299 non-null  float64\n 61  human_development_index                     319127 non-null  float64\n 62  population                                  429435 non-null  int64  \n 63  excess_mortality_cumulative_absolute        13411 non-null   float64\n 64  excess_mortality_cumulative                 13411 non-null   float64\n 65  excess_mortality                            13411 non-null   float64\n 66  excess_mortality_cumulative_per_million     13411 non-null   float64\n\n'

In [4]:
'''
KİMLİK BİLGİLERİ
iso_code	Ülkenin 3 harfli kodu (TUR, USA gibi)
continent	Kıta 
date	Tarih
'''

'\nKİMLİK BİLGİLERİ\niso_code\tÜlkenin 3 harfli kodu (TUR, USA gibi)\ncontinent\tKıta \ndate\tTarih\n'

In [5]:
'''
VAKA & ÖLÜM VERİLERİ
total_cases	O tarihe kadar toplam kümülatif vaka sayısı
new_cases	O günkü yeni vaka sayısı
new_cases_smoothed	Yeni vakaların 7 günlük hareketli ortalaması 
total_deaths / new_deaths / new_deaths_smoothed	Aynı mantık, ölüm için
*_per_million uzantılı olanlar	Yukarıdakilerin milyon kişi başına normalize edilmiş hali — 
ülkeler arası karşılaştırma için bunları kullanacağız
'''

'\nVAKA & ÖLÜM VERİLERİ\ntotal_cases\tO tarihe kadar toplam kümülatif vaka sayısı\nnew_cases\tO günkü yeni vaka sayısı\nnew_cases_smoothed\tYeni vakaların 7 günlük hareketli ortalaması \ntotal_deaths / new_deaths / new_deaths_smoothed\tAynı mantık, ölüm için\n*_per_million uzantılı olanlar\tYukarıdakilerin milyon kişi başına normalize edilmiş hali — \nülkeler arası karşılaştırma için bunları kullanacağız\n'

In [6]:
'''
SALGININ ŞİDDETİ (REPRODUCTİON & HASTANE)
reproduction_rate	R değeri — bir hastanın ortalama kaç kişiyi enfekte ettiği
(1'in üstü = yayılıyor, altı = yavaşlıyor)
icu_patients / icu_patients_per_million	Yoğun bakımdaki hasta sayısı
hosp_patients / hosp_patients_per_million	Hastanede yatan hasta sayısı
weekly_icu_admissions / weekly_hosp_admissions	Haftalık yeni yoğun bakım/hastane girişleri
(çok az ülke bu veriyi paylaşmış — dolu satır sayısı çok düşük: ~11.000-24.000)
'''

"\nSALGININ ŞİDDETİ (REPRODUCTİON & HASTANE)\nreproduction_rate\tR değeri — bir hastanın ortalama kaç kişiyi enfekte ettiği\n(1'in üstü = yayılıyor, altı = yavaşlıyor)\nicu_patients / icu_patients_per_million\tYoğun bakımdaki hasta sayısı\nhosp_patients / hosp_patients_per_million\tHastanede yatan hasta sayısı\nweekly_icu_admissions / weekly_hosp_admissions\tHaftalık yeni yoğun bakım/hastane girişleri\n(çok az ülke bu veriyi paylaşmış — dolu satır sayısı çok düşük: ~11.000-24.000)\n"

In [7]:
'''
TEST VERİLERİ
total_tests / new_tests	Toplam/günlük yapılan test sayısı
positive_rate	Testlerin yüzde kaçı pozitif çıktı
(yüksekse muhtemelen yeterince test yapılmıyor demektir)
tests_per_case	Bir vaka bulmak için kaç test yapıldı
tests_units	Test sayımının birimi (kişi mi, test sayısı mı — bazı ülkeler farklı sayıyor)
'''

'\nTEST VERİLERİ\ntotal_tests / new_tests\tToplam/günlük yapılan test sayısı\npositive_rate\tTestlerin yüzde kaçı pozitif çıktı\n(yüksekse muhtemelen yeterince test yapılmıyor demektir)\ntests_per_case\tBir vaka bulmak için kaç test yapıldı\ntests_units\tTest sayımının birimi (kişi mi, test sayısı mı — bazı ülkeler farklı sayıyor)\n'

In [8]:
'''
AŞI VERİLERİ
total_vaccinations	Toplam yapılan doz sayısı (bir kişi 2 doz olduysa 2 sayılır)
people_vaccinated	En az 1 doz olan kişi sayısı
people_fully_vaccinated	Tam aşılı (2 doz vb.) kişi sayısı
total_boosters	Yapılan hatırlatma (booster) dozu sayısı
*_per_hundred uzantılı	Yüz kişi başına oran
'''

'\nAŞI VERİLERİ\ntotal_vaccinations\tToplam yapılan doz sayısı (bir kişi 2 doz olduysa 2 sayılır)\npeople_vaccinated\tEn az 1 doz olan kişi sayısı\npeople_fully_vaccinated\tTam aşılı (2 doz vb.) kişi sayısı\ntotal_boosters\tYapılan hatırlatma (booster) dozu sayısı\n*_per_hundred uzantılı\tYüz kişi başına oran\n'

In [9]:
'''
stringency_index	Hükümetin kısıtlama sertliği endeksi (0-100, kapanma/maske zorunluluğu vb.)
population_density	Nüfus yoğunluğu (km² başına kişi)
median_age	Medyan yaş
aged_65_older / aged_70_older	Nüfusun 65/70 yaş üstü yüzdesi
gdp_per_capita	Kişi başı GSYH
extreme_poverty	Aşırı yoksulluk oranı
cardiovasc_death_rate	Kardiyovasküler hastalık ölüm oranı
diabetes_prevalence	Diyabet yaygınlığı
female_smokers / male_smokers	Sigara içme oranları (cinsiyete göre)
handwashing_facilities	El yıkama imkanına erişim oranı
hospital_beds_per_thousand	Bin kişiye düşen hastane yatağı
life_expectancy	Ortalama yaşam beklentisi
human_development_index	İnsani gelişmişlik endeksi (HDI)
population	Toplam nüfus
'''

'\nstringency_index\tHükümetin kısıtlama sertliği endeksi (0-100, kapanma/maske zorunluluğu vb.)\npopulation_density\tNüfus yoğunluğu (km² başına kişi)\nmedian_age\tMedyan yaş\naged_65_older / aged_70_older\tNüfusun 65/70 yaş üstü yüzdesi\ngdp_per_capita\tKişi başı GSYH\nextreme_poverty\tAşırı yoksulluk oranı\ncardiovasc_death_rate\tKardiyovasküler hastalık ölüm oranı\ndiabetes_prevalence\tDiyabet yaygınlığı\nfemale_smokers / male_smokers\tSigara içme oranları (cinsiyete göre)\nhandwashing_facilities\tEl yıkama imkanına erişim oranı\nhospital_beds_per_thousand\tBin kişiye düşen hastane yatağı\nlife_expectancy\tOrtalama yaşam beklentisi\nhuman_development_index\tİnsani gelişmişlik endeksi (HDI)\npopulation\tToplam nüfus\n'

In [10]:
'''
Aşırı Ölüm (Excess Mortality)
excess_mortality	Beklenen ölüm sayısına göre fazladan ölüm yüzdesi
(COVID'in resmi sayılara yansımayan gerçek etkisini gösterir)
excess_mortality_cumulative	Kümülatif hali
excess_mortality_cumulative_absolute	Mutlak sayı olarak
excess_mortality_cumulative_per_million	Milyon kişi başına 
'''

"\nAşırı Ölüm (Excess Mortality)\nexcess_mortality\tBeklenen ölüm sayısına göre fazladan ölüm yüzdesi\n(COVID'in resmi sayılara yansımayan gerçek etkisini gösterir)\nexcess_mortality_cumulative\tKümülatif hali\nexcess_mortality_cumulative_absolute\tMutlak sayı olarak\nexcess_mortality_cumulative_per_million\tMilyon kişi başına \n"

In [11]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,4.118040e+05,4.101590e+05,4.089290e+05,4.118040e+05,410608.000000,409378.000000,411804.000000,410159.000000,408929.000000,411804.000000,...,243817.000000,161741.000000,290689.000000,390299.000000,319127.000000,4.294350e+05,1.341100e+04,13411.000000,13411.000000,13411.000000
mean,7.365292e+06,8.017360e+03,8.041026e+03,8.125957e+04,71.852139,72.060828,112096.199420,122.357073,122.713852,835.514337,...,33.097758,50.649390,3.106895,73.702098,0.722178,1.520336e+08,5.604765e+04,9.766431,10.925353,1772.666404
std,4.477582e+07,2.296649e+05,8.661611e+04,4.411901e+05,1368.322990,513.636565,162240.412405,1508.778585,559.701663,1134.932641,...,13.853952,31.905236,2.549168,7.387914,0.149237,6.975408e+08,1.568691e+05,12.040658,24.560706,1991.892770
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.700000,1.190000,0.100000,53.280000,0.390000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2936.450000
25%,6.280750e+03,0.000000e+00,0.000000e+00,4.300000e+01,0.000000,0.000000,1916.100000,0.000000,0.000000,24.570000,...,22.600000,20.860000,1.300000,69.500000,0.600000,5.237980e+05,1.765000e+02,2.060000,-1.500000,116.875000
50%,6.365300e+04,0.000000e+00,1.200000e+01,7.990000e+02,0.000000,0.000000,29145.480000,0.000000,2.790000,295.090000,...,33.100000,49.540000,2.500000,75.050000,0.740000,6.336393e+06,6.815200e+03,8.130000,5.660000,1270.800000
75%,7.582720e+05,0.000000e+00,3.132900e+02,9.574000e+03,0.000000,3.140000,156770.190000,0.000000,56.250000,1283.820000,...,41.500000,82.500000,4.210000,79.460000,0.830000,3.296952e+07,3.912804e+04,15.160000,15.575000,2883.025000
max,7.758668e+08,4.423623e+07,6.319461e+06,7.057132e+06,103719.000000,14817.000000,763598.600000,241758.230000,34536.890000,6601.110000,...,78.100000,100.000000,13.800000,86.750000,0.960000,7.975105e+09,1.349776e+06,78.080000,378.220000,10293.520000

In [12]:
print(df['location'].unique())

['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt' 'El Salvador'
 'England' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Europe' 'European Union (27)' 'Faroe Islands' 'Falkland Islands' 'Fiji'
 'Finland' 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia'
 'Georgia' 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada'
 'Guadeloupe' 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'High-income countries' 'Honduras' 'Hong Kong' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man'
 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania'
 'Low-income countries' 'Lower-middle-income countries' 'Luxembourg'
 'Macao' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mauritius' 'Mayotte'
 'Mexico' 'Micronesia (country)' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niger' 'Nigeria' 'Niue' 'North America' 'North Korea' 'North Macedonia'
 'Northern Cyprus' 'Northern Ireland' 'Northern Mariana Islands' 'Norway'
 'Oceania' 'Oman' 'Pakistan' 'Palau' 'Palestine' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Pitcairn' 'Poland'
 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion' 'Romania' 'Russia' 'Rwanda'
 'Saint Barthelemy' 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)'
 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa'
 'South America' 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan'
 'Tanzania' 'Thailand' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago'
 'Tunisia' 'Turkey' 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu'
 'Uganda' 'Ukraine' 'United Arab Emirates' 'United Kingdom'
 'United States' 'United States Virgin Islands'
 'Upper-middle-income countries' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Vatican' 'Venezuela' 'Vietnam' 'Wales' 'Wallis and Futuna'
 'Western Sahara' 'World' 'Yemen' 'Zambia' 'Zimbabwe']

In [13]:
#Kıta bazlı inceleme yapmak istediğim zaman ayrı bir df daha kullanışlı olur.
continents = ['Africa', 'Asia', 'Europe', 'North America', 
              'South America', 'Oceania']

income_groups = ['High-income countries', 'Low-income countries',
                  'Lower-middle-income countries', 'Upper-middle-income countries']

world_and_eu = ['World', 'European Union (27)']

uk_subregions = ['England', 'Scotland', 'Wales', 'Northern Ireland']

# 1. Sadece gerçek, bağımsız ülkeler — ana analizlerimiz için
df_countries = df[~df['location'].isin(continents + income_groups + world_and_eu + uk_subregions)].copy()

# 2. Sadece kıta toplamları
df_continents = df[df['location'].isin(continents)].copy()

# 3. Sadece gelir grubu toplamları
df_income_groups = df[df['location'].isin(income_groups)].copy()

print(f"Ülke bazlı veri: {len(df_countries)} satır")
print(f"Kıta verisi: {len(df_continents)} satır")
print(f"Gelir grubu verisi: {len(df_income_groups)} satır")

Ülke bazlı veri: 397676 satır
Kıta verisi: 10071 satır
Gelir grubu verisi: 11746 satır

In [14]:
print(df_countries['continent'].isnull().sum())

0

In [15]:
key_columns = ['location', 'date', 'total_cases', 'new_cases_smoothed', 
               'total_deaths', 'new_deaths_smoothed', 
               'total_cases_per_million', 'total_deaths_per_million',
               'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
               'aged_65_older', 'population']

missing_key = df_countries[key_columns].isnull().sum()
missing_pct_key = (missing_key / len(df_countries)) * 100
print(missing_pct_key.sort_values(ascending=False))

people_fully_vaccinated_per_hundred    84.929692
people_vaccinated_per_hundred          84.154689
aged_65_older                          19.133667
new_cases_smoothed                      2.206570
new_deaths_smoothed                     2.093664
total_deaths_per_million                1.498707
total_cases                             1.498707
total_cases_per_million                 1.498707
total_deaths                            1.498707
date                                    0.000000
location                                0.000000
population                              0.000000
dtype: float64

In [16]:
# Her ülke için eksik total_cases'in tarih aralığına bakalım (ilk 5 örnek)
missing_cases = df_countries[df_countries['total_cases'].isnull()]
print(missing_cases.groupby('location')['date'].agg(['min', 'max', 'count']).head(10))

                      min         max  count
location
Argentina      2020-01-01  2020-01-04      4
Czechia        2024-08-05  2024-08-12      8
East Timor     2021-02-12  2023-11-22   1014
Estonia        2024-08-05  2024-08-12      8
Faroe Islands  2021-01-29  2022-02-26    394
Hong Kong      2020-01-31  2024-08-10   1654
India          2024-08-05  2024-08-12      8
Italy          2024-08-05  2024-08-07      3
Lithuania      2024-08-05  2024-08-14     10
Macao          2021-02-08  2023-04-13    795

In [17]:
# 1. Önce raporlama durumu flag'ini oluştur (orijinal boşluğu kaybetmeden)
df_countries['data_reported'] = df_countries['total_cases'].notna()

# 2. Ülke bazında sıralama (ffill için gerekli)
df_countries = df_countries.sort_values(['location', 'date']).copy()

# 3. Analiz için ayrı bir kopya oluştur (orijinal veri saklı kalsın)
df_countries_analysis = df_countries.copy()

# 4. Kümülatif kolonlar için forward fill (yalnızca analiz versiyonunda)
cumulative_cols = ['total_cases', 'total_deaths', 'total_cases_per_million', 'total_deaths_per_million']
df_countries_analysis[cumulative_cols] = df_countries_analysis.groupby('location')[cumulative_cols].ffill()

# 5. Günlük kolonlar için 0 ile doldurma (yalnızca analiz versiyonunda)
daily_cols = ['new_cases', 'new_deaths', 'new_cases_smoothed', 'new_deaths_smoothed']
df_countries_analysis[daily_cols] = df_countries_analysis[daily_cols].fillna(0)

# 6. Verisi girilmeyen ülke/tarih kombinasyonlarını ayrı tut
missing_country_dates = (
    df_countries[df_countries['data_reported'] == False]
    [['location', 'date', 'total_cases', 'new_cases', 'new_deaths']]
    .copy()
)

# 7. Analiz dataframe'i kullanmaya devam et
# Eğer ileride mevcut DF ile çalışacaksan bunu kullan:
# df_countries = df_countries_analysis

# 8. Kontrol
print('Analiz boşluk kontrolü:')
print(df_countries_analysis[cumulative_cols + daily_cols].isnull().sum())
print('\nRaporlanan / raporlanmayan satırlar:')
print(df_countries['data_reported'].value_counts())
print('\nÖrnek eksik veri satırları:')
print(missing_country_dates.head())

Analiz boşluk kontrolü:
total_cases                 4498
total_deaths                4498
total_cases_per_million     4498
total_deaths_per_million    4498
new_cases                      0
new_deaths                     0
new_cases_smoothed             0
new_deaths_smoothed            0
dtype: int64

Raporlanan / raporlanmayan satırlar:
data_reported
True     391716
False      5960
Name: count, dtype: int64

Örnek eksik veri satırları:
        location        date  total_cases  new_cases  new_deaths
15066  Argentina  2020-01-01          NaN        NaN         NaN
15067  Argentina  2020-01-02          NaN        NaN         NaN
15068  Argentina  2020-01-03          NaN        NaN         NaN
15069  Argentina  2020-01-04          NaN        NaN         NaN
93758    Czechia  2024-08-05          NaN        NaN         NaN

In [19]:
# aged_65_older boş olan ülkeleri bul
missing_age = df_countries[df_countries['aged_65_older'].isnull()]['location'].unique()
print(f"Toplam {len(missing_age)} ülkede aged_65_older verisi hiç yok:")
print(missing_age)

Toplam 47 ülkede aged_65_older verisi hiç yok:
['American Samoa' 'Andorra' 'Anguilla' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Dominica' 'Falkland Islands'
 'Faroe Islands' 'French Guiana' 'Gibraltar' 'Greenland' 'Guadeloupe'
 'Guernsey' 'Isle of Man' 'Jersey' 'Kosovo' 'Liechtenstein'
 'Marshall Islands' 'Martinique' 'Mayotte' 'Monaco' 'Montserrat' 'Nauru'
 'Niue' 'Northern Cyprus' 'Northern Mariana Islands' 'Palau' 'Pitcairn'
 'Reunion' 'Saint Barthelemy' 'Saint Helena' 'Saint Kitts and Nevis'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon' 'San Marino'
 'Sint Maarten (Dutch part)' 'Syria' 'Taiwan' 'Tokelau'
 'Turks and Caicos Islands' 'Tuvalu' 'Vatican' 'Wallis and Futuna'
 'Western Sahara']